import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const profileUrl = new URL('./package.json', import.meta.url)
const patchUrl = new URL('./cordis.patch.yml', import.meta.url)
const lockUrl = new URL('./pnpm-lock.yaml', import.meta.url)
const npmrcUrl = new URL('./.npmrc', import.meta.url)
const runtimePatchUrl = new URL('./patches/@dingtalk-real-ai__dsh-dingtalk@0.6.2.patch', import.meta.url)
const balanceUrl = new URL('../../extensions/dsbalance-bundle/client.js', import.meta.url)

test('web profile keeps the original balance bundle and uses the pinned DingTalk status seam', async () => {
  const [profile, patch, lock, npmrc, runtimePatch, balance] = await Promise.all([
    readFile(profileUrl, 'utf8').then(JSON.parse),
    readFile(patchUrl, 'utf8'),
    readFile(lockUrl, 'utf8'),
    readFile(npmrcUrl, 'utf8'),
    readFile(runtimePatchUrl, 'utf8'),
    readFile(balanceUrl, 'utf8'),
  ])
  assert.equal(profile.dependencies['@dingtalk-real-ai/dsh-dingtalk'], '0.6.2')
  assert.equal(profile.pnpm?.patchedDependencies?.['@dingtalk-real-ai/dsh-dingtalk@0.6.2'], 'patches/@dingtalk-real-ai__dsh-dingtalk@0.6.2.patch')
  assert.equal(profile.dependencies['@local/dsh-dingtalk-status'], 'link:/Users/marcus/.dsh/extensions/dsh-dingtalk-status')
  assert.equal(profile.dependencies['@local/dsh-imessage-bridge'], undefined)
  assert.ok(profile.dsh.profile.bundles.includes('@local/dsh-dsbalance'))
  assert.ok(profile.dsh.profile.bundles.includes('@dingtalk-real-ai/dsh-dingtalk'))
  assert.ok(profile.dsh.profile.bundles.includes('@local/dsh-dingtalk-status'))
  assert.equal(profile.dsh.profile.bundles.includes('@local/dsh-imessage-bridge'), false)

  assert.match(patch, /id: dingtalk-channel/)
  assert.match(patch, /workspace: \/Users\/marcus\/Desktop/)
  assert.match(patch, /senderAccess: owner/)
  assert.match(patch, /groupAccess: none/)
  assert.match(patch, /imageMode: auto/)
  assert.match(patch, /tools:\s*\n\s+enabled: true/)
  assert.match(patch, /debug: false/)
  assert.match(patch, /consoleCardTemplateId: f42ee85c-bdb9-4197-b8b7-4379e9b64878\.schema/)
  assert.match(patch, /defaultDingTalkPresetId: reliable-development/)
  assert.match(patch, /id: dsh-dingtalk-status/)
  assert.match(patch, /clientIdRef: DINGTALK_CLIENT_ID/)
  assert.match(patch, /clientSecretRef: DINGTALK_CLIENT_SECRET/)
  assert.doesNotMatch(patch, /^\s*(?:clientId|clientSecret|ownerStaffId):/im)
  assert.doesNotMatch(patch, /bind\s+[^#\n]+/i)

  assert.match(lock, /['"]?@dingtalk-real-ai\/dsh-dingtalk['"]?:\s*\n\s+specifier: 0\.6\.2/)
  assert.match(lock, /\/\@dingtalk-real-ai\/dsh-dingtalk@0\.6\.2/)
  assert.match(lock, /dingtalk-stream:/)
  assert.match(lock, /patchedDependencies:/)
  assert.match(lock, /patch_hash=/)
  assert.doesNotMatch(lock, /@local\/dsh-imessage-bridge/)
  assert.match(npmrc, /^registry=https:\/\/registry\.npmjs\.org\/$/m)
  assert.match(npmrc, /^ignore-workspace-root-check=true$/m)
  for (const contract of ['/menu', '/sessions', '/session use', '/artifacts', '/send <序号>', '/replies', '/resend <序号|turn:编号>', '/models', '/effort']) assert.match(runtimePatch, new RegExp(contract.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')))
  assert.match(runtimePatch, /send-by-bot/)
  assert.match(runtimePatch, /DWS_CLIENT_SECRET/)
  assert.match(runtimePatch, /机器人附件可用/)
  assert.match(runtimePatch, /DeliveryStore/)
  assert.match(runtimePatch, /delivery-pending\.json/)
  assert.match(runtimePatch, /recoverPending/)
  assert.match(runtimePatch, /DINGTALK_TIMEOUT/)
  assert.match(runtimePatch, /DINGTALK_ROUTE_TTL_MS/)
  assert.match(runtimePatch, /source\?\.kind === 'user'/)
  assert.match(runtimePatch, /sessionQuery/)
  assert.match(runtimePatch, /listSessions\(\)/)
  assert.match(runtimePatch, /resolveCallConfig/)
  assert.match(runtimePatch, /consoleCardTemplateId/)
  assert.match(runtimePatch, /defaultDingTalkPresetId/)
  assert.match(runtimePatch, /presetOverrides/)
  assert.match(runtimePatch, /presetSlot/)
  assert.match(runtimePatch, /submit_form_fields/)
  assert.match(runtimePatch, /userPrivateData/)

  // Balance contract: one compact row, two independent provider reads, and
  // amount-only official account links.
  assert.match(balance, /const inject = \['slots', 'timer'\]/)
  assert.doesNotMatch(balance, /modelDirectories/)
  assert.match(balance, /provider=\' \+ brand\.apiProvider/)
  assert.match(balance, /apiProvider: 'deepseek'/)
  assert.match(balance, /apiProvider: 'zhipu'/)
  assert.match(balance, /const BRAND_LIST = \[BRANDS\.deepseek, BRANDS\.zhipu\]/)
  assert.match(balance, /Promise\.all\(BRAND_LIST\.map\(loadProvider\)\)/)
  assert.match(balance, /timer\.interval\(loadAll, 60000\)/)
  assert.match(balance, /setInterval\(loadAll, 60000\)/)
  assert.match(balance, /\[brand\.key\]: \{ data, error: null \}/)
  assert.match(balance, /\[brand\.key\]: \{ data: null, error: errorText\(cause\) \}/)
  assert.match(balance, /React\.createElement\('span', \{ className: 'dsbalance-label' \}, '余额'\)/)
  assert.match(balance, /className: 'dsbalance-badge'/)
  assert.match(balance, /style: \{ background: brand\.dot \}/)
  assert.doesNotMatch(balance, /API 余额/)
  assert.doesNotMatch(balance, /充值/)
  assert.match(balance, /topUpUrl: 'https:\/\/platform\.deepseek\.com\/top_up'/)
  assert.match(balance, /topUpUrl: 'https:\/\/open\.bigmodel\.cn\/finance-center\/finance\/overview'/)
  assert.match(balance, /className: 'dsbalance-value'/)
  assert.match(balance, /href: brand\.topUpUrl/)
  assert.match(balance, /target: '_blank'/)
  assert.match(balance, /return amount === null \? '—'/)
  assert.match(balance, /title: '余额：展开侧栏查看 DS 与 GLM'/)
})
