import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const clientUrl = new URL('./client.js', import.meta.url)

test('虾缸 is a commandUi action and has no session/heartbeat inference', async () => {
  const source = await readFile(clientUrl, 'utf8')
  assert.match(source, /var module = \{ exports: \{\} \}/)
  assert.match(source, /var exports = module\.exports/)
  assert.match(source, /id: '@local\/dsh-shrimp-run-status'/)
  assert.match(source, /const inject = \['slots', 'commandUi'\]/)
  assert.match(source, /commandUi\.register\(/)
  assert.match(source, /name: '虾缸'/)
  assert.match(source, /kind: 'action'/)
  assert.match(source, /run: \(session\) => dispatchOpen\(session\?\.sessionId\)/)
  assert.match(source, /shrimp:tank-open/)
  assert.match(source, /conversation\.input\.dock/)
  assert.doesNotMatch(source, /conversation\.input\.overlay/)
  assert.doesNotMatch(source, /conversation\.session\.run-status/)
  assert.doesNotMatch(source, /inputTriggers/)
  assert.doesNotMatch(source, /runningCalls|heartbeat|heartbeat_gzh_publish|useSession|shrimp:request-library/)
})

test('input card reads only canonical tank proxy paths and polls while open', async () => {
  const source = await readFile(clientUrl, 'utf8')
  assert.match(source, /tankApi\('\/api\/v1\/dsh\/shrimps', \{ signal \}\)/)
  assert.match(source, /tankApi\('\/api\/v1\/runs\?limit=50', \{ signal \}\)/)
  assert.match(source, /\/api\/v1\/runs\/\$\{encodeURIComponent\(runId\)\}\/summary/)
  assert.doesNotMatch(source, /\/api\/v1\/runs\/\$\{encodeURIComponent\(runId\)\}\/status/)
  assert.doesNotMatch(source, /\/api\/v1\/pipelines/)
  assert.match(source, /window\.setTimeout\(\(\) => \{ void tick\(\) \}, 4000\)/)
  assert.match(source, /window\.clearTimeout\(timer\)/)
  assert.doesNotMatch(source, /setInterval|clearInterval/)
  assert.match(source, /AbortController/)
  assert.match(source, /controller\?\.abort\(\)/)
  assert.match(source, /summaryError/)
  assert.match(source, /Promise\.all\(groups\.map/)
  assert.match(source, /isActiveStatus\(summary\.status\) \? \{ \.\.\.group, summary \} : null/)
  assert.match(source, /if \(!alive \|\| error\?\.name === 'AbortError'\) return/)
  assert.match(source, /setState\(\{ phase: 'loading', groups: \[\], shrimps: \[\], error: '' \}\)/)
  assert.match(source, /if \(!open\) return null/)
  assert.match(source, /order: 10/)
  assert.match(source, /width:calc\(100% - \(var\(--dsh-composer-side-clearance,16px\) \* 2\)\)/)
  assert.match(source, /max-width:var\(--dsh-composer-card-max-width,780px\)/)
  assert.match(source, /max-height:min\(48vh,480px\)/)
  assert.doesNotMatch(source, /position:(?:absolute|fixed)/)
  assert.doesNotMatch(source, /\binset\s*:/)
  assert.doesNotMatch(source, /z-index|dsh-shrimp-tank-(?:backdrop|overlay)|aria-modal|body\.style\.overflow/)
})

test('input card close/reopen, responsive overflow, and reduced motion are explicit', async () => {
  const source = await readFile(clientUrl, 'utf8')
  assert.match(source, /event\.key === 'Escape'/)
  assert.match(source, /role: 'region'/)
  assert.match(source, /'aria-labelledby': 'dsh-shrimp-tank-title'/)
  assert.match(source, /className: 'dsh-shrimp-tank-close'/)
  assert.match(source, /'关闭'/)
  assert.match(source, /都在休息/)
  assert.match(source, /现在没有虾在运行/)
  assert.match(source, /\$\{state\.groups\.length\}只运行中/)
  assert.doesNotMatch(source, /className: 'dsh-shrimp-tank-node-progress'/)
  assert.doesNotMatch(source, /dsh-shrimp-tank-node-progress/)
  assert.match(source, /重新读取/)
  assert.match(source, /NodeStepper/)
  assert.match(source, /dsh-shrimp-tank-stepper/)
  assert.match(source, /dsh-shrimp-tank-progress-bar/)
  assert.match(source, /dsh-shrimp-tank-stepper.*overflow-x:auto/s)
  assert.doesNotMatch(source, /NodeTrack|NodeTimeline|dsh-shrimp-tank-node-track|dsh-shrimp-tank-tabs/)
  assert.doesNotMatch(source, /dsh-shrimp-tank-swimmer-route|identity\.route|IDLE_SWIMMERS|皮皮虾@平安/)
  assert.match(source, /projectPublishedShrimps/)
  assert.match(source, /IdleView\(\{ shrimps \}\)/)
  assert.match(source, /\[data-composer-seat\]:has\(\.dsh-shrimp-tank-card\)>:has\(>\[data-slot="conversation\.input\.dock"\]>.dsh-shrimp-tank-card\)/)
  assert.doesNotMatch(source, /\[data-composer-seat\]:has\(\.dsh-shrimp-tank-card\) \[data-slot="conversation\.input\.dock"\]\{margin-bottom/)
  assert.match(source, /margin:0 auto calc\(var\(--dsh-composer-stack-gap,6px\) \* -1\)/)
  assert.match(source, /\[data-composer-seat\]:has\(\.dsh-shrimp-tank-card\) \[data-composer-card\]/)
  assert.match(source, /@keyframes dsh-shrimp-stepper-pulse/)
  assert.match(source, /@keyframes dsh-shrimp-stepper-highlight/)
  assert.match(source, /background-size:200% 100%/)
  assert.match(source, /const running = node\.state === 'running'/)
  assert.match(source, /node\.state === 'queued' \? '排队中'/)
  assert.match(source, /node\.state === 'failed' \? '失败' : node\.state === 'blocked' \? '已阻断'/)
  assert.match(source, /@media\(prefers-reduced-motion:reduce\).*dsh-shrimp-tank-stepper-item/s)
  assert.match(source, /dsh-shrimp-tank-progress-bar span\{transition:none!important\}/)
  assert.match(source, /'aria-label': '已发布虾'/)
  assert.match(source, /@media\(max-width:760px\)/)
  assert.match(source, /@media\(prefers-reduced-motion:reduce\)/)
  assert.match(source, /dsh-shrimp-tank-swimmer.*transform/s)
  assert.match(source, /🦐/)
  assert.match(source, /dsh-shrimp-swim-one/)
  assert.match(source, /index < 4 \? ` is-path-\$\{index \+ 1\}` : ''/)
  assert.match(source, /onPointerMove: index < 4 \? pointerAvoid : undefined/)
})
