
(() => {
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const spec=JSON.parse($('#magazine-spec').textContent.trim());
const sizes={a4:{w:794,h:1123,top:220,footer:123,coverTop:380,coverFooter:193},'16x9':{w:1280,h:720,top:96,footer:72,coverTop:210,coverFooter:96}};
const size=sizes[spec.canvas_type]||sizes.a4; let edit=false,selected=null,drag=null,resize=null,savedRange=null;
document.title=spec.title||'Magazine Editor'; document.documentElement.style.setProperty('--primary',spec.theme?.primary||'#f05a22'); document.documentElement.style.setProperty('--ink',spec.theme?.ink||'#1f2933'); document.documentElement.style.setProperty('--paper',spec.theme?.paper||'#fffdf8'); document.documentElement.style.setProperty('--page-w',size.w+'px'); document.documentElement.style.setProperty('--page-h',size.h+'px');
const deck=$('#deck'); deck.classList.add(spec.canvas_type==='16x9'?'canvas-16x9':'canvas-a4');
function esc(s){return String(s||'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function render(){deck.innerHTML=''; (spec.pages||[]).forEach((p,i)=>{const isCover=p.kind==='cover'; const page=document.createElement('section'); page.className='page '+(isCover?'cover':''); page.dataset.pageId=p.id||('p'+(i+1)); page.style.setProperty('--top-h',(p.top?.height || (isCover?size.coverTop:size.top))+'px'); page.style.setProperty('--footer-h',(p.footer?.height || (isCover?size.coverFooter:size.footer))+'px');
const bg=document.createElement('div'); bg.className='layer-bg selectable'; bg.dataset.layerName='背景图'; bg.dataset.layerType='background'; bg.style.background=p.background?.color||spec.theme?.paper||'#fffdf8'; if(p.background?.src)bg.style.backgroundImage=`url(${p.background.src})`,bg.style.backgroundSize='cover'; page.appendChild(bg);
page.appendChild(imageLayer('top',p.top,'顶部图')); page.appendChild(imageLayer('footer',p.footer,'页脚图'));
(p.components||[]).forEach(c=>page.appendChild(component(c))); deck.appendChild(page)}); initAll();}
function imageLayer(type,c={},name){const d=document.createElement('div'); d.className='layer-'+type+' selectable'; d.dataset.layerType=type; d.dataset.layerName=name; d.style.zIndex=c.z||5; d.style.setProperty('--op-start',c.opStart ?? 1); d.style.setProperty('--op-end',c.opEnd ?? 1); const src=c.src||svgBand(type); d.innerHTML=`<img src="${esc(src)}" alt="${name}">`; return d}
function svgBand(type){const col=encodeURIComponent(spec.theme?.primary||'#f05a22'); const h=type==='top'?260:140; return `data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1600' height='${h}' viewBox='0 0 1600 ${h}'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop stop-color='%23fff8f0'/><stop offset='1' stop-color='${col}' stop-opacity='.32'/></linearGradient></defs><rect width='1600' height='${h}' fill='url(%23g)'/><path d='M0 ${h*0.65} C320 ${h*0.25},620 ${h*0.9},960 ${h*0.48} S1320 ${h*0.65},1600 ${h*0.25}' fill='none' stroke='${col}' stroke-opacity='.34' stroke-width='16'/></svg>`}
function component(c){const w=document.createElement('div'); w.className='widget '+(c.type==='image'?'image-widget ':'')+(c.className||''); w.dataset.layerName=c.name||c.type||'组件'; w.dataset.componentType=c.type||'text'; Object.assign(w.style,{left:(c.x||0)+'px',top:(c.y||0)+'px',width:(c.w||200)+'px',height:(c.h||100)+'px',zIndex:c.z||30,opacity:c.opacity??1}); if(c.type==='image'){w.innerHTML=`<div class="image-slot">${c.src?`<img src="${esc(c.src)}" alt="${esc(c.name||'图片')}">`:'<div class="img-hint">双击替换图片</div>'}</div>`}else{w.innerHTML=`<div class="widget-body" contenteditable="true">${c.html||'<p>直接编辑文字</p>'}</div>`} return w}
function px(v){return parseFloat(String(v||'0').replace('px',''))||0} function currentPage(){return selected?.closest?.('.page')||$('.page')} function selectable(){return $$('.layer-bg,.layer-top,.layer-footer,.widget')} function zNum(el){return parseInt(el.style.zIndex||getComputedStyle(el).zIndex)||0}
function setEdit(v){edit=v;document.body.classList.toggle('edit-mode',v);$('#editToggle').textContent=v?'关闭编辑':'开启编辑';if(!v)deselect()} function deselect(){selectable().forEach(x=>x.classList.remove('selected'));selected=null;$('#propPanel').classList.remove('active','for-image','for-bg')} function select(el){if(!edit||!el)return;selectable().forEach(x=>x.classList.remove('selected'));selected=el;el.classList.add('selected');syncPanel(el)}
function syncPanel(el){const p=$('#propPanel');p.classList.add('active');const isImg=el.classList.contains('layer-top')||el.classList.contains('layer-footer')||el.classList.contains('image-widget');p.classList.toggle('for-image',isImg);p.classList.toggle('for-bg',el.classList.contains('layer-bg'));$('#propTitle').textContent=el.dataset.layerName||'属性';$('#layerOpacity').value=Math.round((parseFloat(el.style.opacity||1))*100);$('#imgTopOpacity').value=Math.round(parseFloat(el.style.getPropertyValue('--op-start')||1)*100);$('#imgBottomOpacity').value=Math.round(parseFloat(el.style.getPropertyValue('--op-end')||1)*100)}
function chooseImage(cb){const picker=$('#imagePicker');picker.onchange=()=>{const f=picker.files[0];if(!f)return;const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(f);picker.value=''};picker.click()} function replaceImageLayer(layer){if(!layer)return;chooseImage(src=>{let img=layer.querySelector('img');if(!img){img=document.createElement('img');layer.appendChild(img)}img.src=src;select(layer)})} function selectedOrPageLayer(type){if(selected?.dataset?.layerType===type)return selected;return currentPage().querySelector(type==='top'?'.layer-top':'.layer-footer')} function setBg(){const bg=currentPage().querySelector('.layer-bg');chooseImage(src=>{bg.style.backgroundImage=`url(${src})`;bg.style.backgroundSize='cover';select(bg)})}
function initSelectableLayer(el){el.addEventListener('mousedown',e=>{if(!edit)return;if(el.classList.contains('widget'))return;e.stopPropagation();select(el)}); if(el.classList.contains('layer-top')||el.classList.contains('layer-footer')) el.addEventListener('dblclick',e=>{if(edit){e.stopPropagation();replaceImageLayer(el)}})}
function initWidget(w){if(w.dataset.ready)return;w.dataset.ready='1';w.addEventListener('mousedown',e=>{if(edit){e.stopPropagation();select(w)}});w.addEventListener('dblclick',e=>{if(edit&&w.classList.contains('image-widget')){e.stopPropagation();replaceWidgetImage(w)}});const c=document.createElement('div');c.className='widget-control';c.innerHTML='<div class="drag-handle">拖动</div><button class="delete-btn">×</button>'+['nw','n','ne','e','se','s','sw','w'].map(d=>`<i class="resize-handle ${d}" data-dir="${d}"></i>`).join('');w.appendChild(c);c.querySelector('.drag-handle').onmousedown=e=>startDrag(e,w);c.querySelector('.delete-btn').onclick=e=>{e.stopPropagation();w.remove();deselect()};c.querySelectorAll('.resize-handle').forEach(h=>h.onmousedown=e=>startResize(e,w,h.dataset.dir))}
function replaceWidgetImage(w){chooseImage(src=>{let slot=w.querySelector('.image-slot')||w.querySelector('.widget-body');slot.innerHTML=`<img src="${src}" style="width:100%;height:100%;object-fit:cover" alt="插图">`})}
function startDrag(e,w){e.preventDefault();e.stopPropagation();select(w);drag={w,startX:e.clientX,startY:e.clientY,l:px(w.style.left),t:px(w.style.top),wi:px(w.style.width),he:px(w.style.height)};document.addEventListener('mousemove',onDrag);document.addEventListener('mouseup',endDrag)} function onDrag(e){if(!drag)return;let l=drag.l+e.clientX-drag.startX,t=drag.t+e.clientY-drag.startY;l=Math.max(0,Math.min(size.w-drag.wi,l));t=Math.max(0,Math.min(size.h-drag.he,t));drag.w.style.left=l+'px';drag.w.style.top=t+'px'} function endDrag(){drag=null;document.removeEventListener('mousemove',onDrag);document.removeEventListener('mouseup',endDrag)}
function startResize(e,w,dir){e.preventDefault();e.stopPropagation();select(w);resize={w,dir,startX:e.clientX,startY:e.clientY,l:px(w.style.left),t:px(w.style.top),wi:px(w.style.width),he:px(w.style.height)};document.addEventListener('mousemove',onResize);document.addEventListener('mouseup',endResize)} function onResize(e){if(!resize)return;let dx=e.clientX-resize.startX,dy=e.clientY-resize.startY,l=resize.l,t=resize.t,w=resize.wi,h=resize.he;if(resize.dir.includes('e'))w=resize.wi+dx;if(resize.dir.includes('s'))h=resize.he+dy;if(resize.dir.includes('w')){w=resize.wi-dx;l=resize.l+dx}if(resize.dir.includes('n')){h=resize.he-dy;t=resize.t+dy}w=Math.max(60,w);h=Math.max(36,h);l=Math.max(0,Math.min(size.w-w,l));t=Math.max(0,Math.min(size.h-h,t));Object.assign(resize.w.style,{left:l+'px',top:t+'px',width:w+'px',height:h+'px'})} function endResize(){resize=null;document.removeEventListener('mousemove',onResize);document.removeEventListener('mouseup',endResize)}
function applyStyle(style){if(!edit)return;let sel=window.getSelection();if(savedRange){sel.removeAllRanges();sel.addRange(savedRange)} if(sel&&sel.rangeCount&&!sel.isCollapsed&&document.body.contains(sel.anchorNode)){const r=sel.getRangeAt(0);const span=document.createElement('span');Object.assign(span.style,style);try{r.surroundContents(span)}catch(err){const frag=r.extractContents();span.appendChild(frag);r.insertNode(span)}savedRange=null}else if(selected){const target=selected.classList.contains('widget')?selected.querySelector('.widget-body'):selected;Object.assign(target.style,style)}} function saveSelection(){if(!edit)return;const sel=window.getSelection();if(sel&&sel.rangeCount&&!sel.isCollapsed&&document.body.contains(sel.anchorNode)){savedRange=sel.getRangeAt(0).cloneRange()}}
function insertText(){const p=currentPage();const div=component({type:'text',name:'新增文字',x:80,y:160,w:280,h:100,z:60,html:'<p>直接编辑文字</p>'});p.appendChild(div);initWidget(div);select(div)} function insertImage(){const p=currentPage();const div=component({type:'image',name:'新增图片',x:Math.floor(size.w*.55),y:160,w:Math.floor(size.w*.25),h:140,z:60});p.appendChild(div);initWidget(div);select(div)} function moveZ(mode){if(!selected)return;let z=zNum(selected);if(mode==='up')z+=1;if(mode==='down')z-=1;if(mode==='top')z=100;if(mode==='bottom')z=1;selected.style.zIndex=z;syncPanel(selected)} function saveHtml(){deselect();const clone=document.documentElement.cloneNode(true);clone.querySelectorAll('.selected').forEach(el=>el.classList.remove('selected'));const html='<!doctype html>\n'+clone.outerHTML;const blob=new Blob([html],{type:'text/html;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=document.title+'.html';a.click();URL.revokeObjectURL(a.href)}
function initAll(){selectable().forEach(initSelectableLayer);$$('.widget').forEach(initWidget)}
render();
$('#editToggle').onclick=()=>setEdit(!edit);$('#insertTextBtn').onclick=insertText;$('#insertImageBtn').onclick=insertImage;$('#replaceTopBtn').onclick=()=>replaceImageLayer(selectedOrPageLayer('top'));$('#replaceFooterBtn').onclick=()=>replaceImageLayer(selectedOrPageLayer('footer'));$('#setBgBtn').onclick=setBg;$('#saveBtn').onclick=saveHtml;$('#printBtn').onclick=()=>window.print();
$('#fontFamily').onchange=e=>applyStyle({fontFamily:e.target.value});$('#fontSize').onchange=e=>applyStyle({fontSize:e.target.value+'px'});$('#fontColor').oninput=e=>applyStyle({color:e.target.value});$('#boldBtn').onclick=()=>applyStyle({fontWeight:'900'});$('#alignLeft').onclick=()=>applyStyle({textAlign:'left'});$('#alignCenter').onclick=()=>applyStyle({textAlign:'center'});$('#alignRight').onclick=()=>applyStyle({textAlign:'right'});$('#layerOpacity').oninput=e=>{if(selected)selected.style.opacity=e.target.value/100};$('#imgTopOpacity').oninput=e=>{if(selected)selected.style.setProperty('--op-start',e.target.value/100)};$('#imgBottomOpacity').oninput=e=>{if(selected)selected.style.setProperty('--op-end',e.target.value/100)};$('#zUp').onclick=()=>moveZ('up');$('#zDown').onclick=()=>moveZ('down');$('#zTop').onclick=()=>moveZ('top');$('#zBottom').onclick=()=>moveZ('bottom');$('#deleteSelected').onclick=()=>{if(selected&&!selected.classList.contains('layer-bg')){selected.remove();deselect()}};
document.addEventListener('selectionchange',saveSelection);document.addEventListener('mousedown',e=>{if(edit&&!e.target.closest('.page,.prop-panel,.editor-toolbar'))deselect()});
})();
